name: smart_chair_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fl_chart: ^1.2.0
  http: ^1.2.0
  shared_preferences: ^2.3.0
  screen_retriever: ^0.1.9
  window_manager: ^0.2.7
  system_tray: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: SmartChairTimes
      fonts:
        - asset: assets/fonts/times.ttf
          weight: 400
        - asset: assets/fonts/timesbd.ttf
          weight: 700
        - asset: assets/fonts/timesbd.ttf
          weight: 800
        - asset: assets/fonts/timesbd.ttf
          weight: 900
    - family: SmartChairKai
      fonts:
        - asset: assets/fonts/kaiu.ttf
          weight: 100
        - asset: assets/fonts/kaiu.ttf
          weight: 200
        - asset: assets/fonts/kaiu.ttf
          weight: 300
        - asset: assets/fonts/kaiu.ttf
          weight: 400
        - asset: assets/fonts/kaiu.ttf
          weight: 500
        - asset: assets/fonts/kaiu.ttf
          weight: 600
        - asset: assets/fonts/kaiu.ttf
          weight: 700
        - asset: assets/fonts/kaiu.ttf
          weight: 800
        - asset: assets/fonts/kaiu.ttf
          weight: 900
  assets:
    - assets/tray_icon.ico
    
