# Generated by Django 6.0.3 on 2026-04-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posturerecord',
            name='fsr_data',
        ),
        migrations.RemoveField(
            model_name='posturerecord',
            name='imu_data',
        ),
        migrations.RemoveField(
            model_name='posturerecord',
            name='tof_data',
        ),
        migrations.AddField(
            model_name='posturerecord',
            name='head_distance_data',
            field=models.JSONField(blank=True, null=True, verbose_name='頭部距離感測數值'),
        ),
        migrations.AddField(
            model_name='posturerecord',
            name='seat_pressure_data',
            field=models.JSONField(blank=True, null=True, verbose_name='座墊壓力感測數值'),
        ),
        migrations.AddField(
            model_name='posturerecord',
            name='tilt_angle_data',
            field=models.JSONField(blank=True, null=True, verbose_name='傾斜角度感測數值'),
        ),
    ]
