# Generated by Django 6.0.3 on 2026-05-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_posturerecord_fsr_data_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="posturerecord",
            name="head_distance_data",
        ),
        migrations.RemoveField(
            model_name="posturerecord",
            name="tilt_angle_data",
        ),
        migrations.AddField(
            model_name="posturerecord",
            name="back_pressure_data",
            field=models.JSONField(
                blank=True, null=True, verbose_name="椅背脊椎壓力感測數值（3點）"
            ),
        ),
        migrations.AlterField(
            model_name="posturerecord",
            name="seat_pressure_data",
            field=models.JSONField(
                blank=True, null=True, verbose_name="座墊壓力感測數值（8點）"
            ),
        ),
    ]
