# Generated by Django 6.0.3 on 2026-05-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_posturerecord_head_distance_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="posturerecord",
            name="physio_advice",
            field=models.TextField(
                blank=True, null=True, verbose_name="AI 物理治療建議"
            ),
        ),
    ]
