# Generated by Django 5.2.13 on 2026-05-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_agentlog_id_alter_chairsession_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chairsession",
            name="baseline_back",
            field=models.JSONField(
                blank=True, null=True, verbose_name="校準基準值（椅背）"
            ),
        ),
        migrations.AddField(
            model_name="chairsession",
            name="baseline_seat",
            field=models.JSONField(
                blank=True, null=True, verbose_name="校準基準值（座墊）"
            ),
        ),
    ]
