# Generated by Django 6.0.3 on 2026-07-20 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_add_display_name_avatar_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="MotorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="時間戳"),
                ),
                ("posture", models.CharField(max_length=20, verbose_name="觸發坐姿")),
                ("motors", models.JSONField(verbose_name="啟動馬達清單")),
                ("reason", models.CharField(max_length=100, verbose_name="觸發原因")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="motor_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="使用者",
                    ),
                ),
            ],
            options={
                "verbose_name": "馬達觸發紀錄",
                "ordering": ["-timestamp"],
            },
        ),
    ]
