# Generated by Django 6.0.3 on 2026-08-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_passwordresetcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentlog",
            name="steps",
            field=models.JSONField(
                blank=True, default=list, verbose_name="ReAct 執行步驟"
            ),
        ),
    ]
