# Generated by Django 5.2.13 on 2026-08-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_agentlog_steps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.TextField(verbose_name="通知內容"),
        ),
    ]
